### ISSUE TITLE
Разворачивание проекта

### ISSUE THREAD

**Issue by teuchezh** [ClusterM/alice-smart-home#1]
Можно подробнее про шаг:
`Разверните проект на веб-сервере с помощью WSGI, не забудьте разрешить заголовки с авторизацией` ?

**Comment by ClusterM** [comment]
https://flask.palletsprojects.com/en/1.1.x/deploying/
https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIPassAuthorization.html
